// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJ8T84ciVPxbsSBQJOZ0lwKquV2l5dSo',
    appId: '1:830901116803:web:823df345e3e0bf804d60b6',
    messagingSenderId: '830901116803',
    projectId: 'hacker-news-99097',
    authDomain: 'hacker-news-99097.firebaseapp.com',
    storageBucket: 'hacker-news-99097.firebasestorage.app',
    measurementId: 'G-L55F449EGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-D4DJzrmCk1lT4RqP1vO2e3fgttybO5g',
    appId: '1:830901116803:android:a064f7b0d58e78764d60b6',
    messagingSenderId: '830901116803',
    projectId: 'hacker-news-99097',
    storageBucket: 'hacker-news-99097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbx03M3f5MGVceOMFa1cv9XnUnfEINro',
    appId: '1:830901116803:ios:b17236d6ddccf8704d60b6',
    messagingSenderId: '830901116803',
    projectId: 'hacker-news-99097',
    storageBucket: 'hacker-news-99097.firebasestorage.app',
    iosBundleId: 'com.example.hackerNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbx03M3f5MGVceOMFa1cv9XnUnfEINro',
    appId: '1:830901116803:ios:b17236d6ddccf8704d60b6',
    messagingSenderId: '830901116803',
    projectId: 'hacker-news-99097',
    storageBucket: 'hacker-news-99097.firebasestorage.app',
    iosBundleId: 'com.example.hackerNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcJ8T84ciVPxbsSBQJOZ0lwKquV2l5dSo',
    appId: '1:830901116803:web:ce80cbfc4decb2db4d60b6',
    messagingSenderId: '830901116803',
    projectId: 'hacker-news-99097',
    authDomain: 'hacker-news-99097.firebaseapp.com',
    storageBucket: 'hacker-news-99097.firebasestorage.app',
    measurementId: 'G-P47H6NQ4PL',
  );
}
